### ISSUE TITLE
Error at Metaphlan2 Markergene database step

### ISSUE THREAD

**Issue by abigailvolk** [sustc-xylab/ARGpore2#1]
Hi All,

I am attempting to download and use your tool. I installed the necessary dependencies in a Conda environment, cloned this repo, and used your directions to begin the database install. However, I'm getting an error at the Metaphlan2 Markergene database step:
```Downloading Metaphlan2 markergene database from git lfs
Updated Git hooks.
Git LFS initialized.
markers.fasta

Building lastdb for Metaphlan2 markergene database
Can't locate Bio/SeqIO.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /fs/ess/PAS1806/Abby/TOOLS/ARGpore2/bin/fastaNameLengh.pl line 23.
BEGIN failed--compilation aborted at /fs/ess/PAS1806/Abby/TOOLS/ARGpore2/bin/fastaNameLengh.pl line 23.
```

Any ideas? Based on the error it seems that I do not have the Bio::SeqIO module. I have tried installing it into my Conda env `conda install -c bioconda perl-bioperl` but am still getting the error.

**Comment by sustc-xylab** [comment]
Hi, thanks for yr interest in our tool. Seems Bio/SeqIO.pm module is missing for your perl, which might be sovled following below protocol


Error： Can't locate Config/General.pm in @INC … 
This error indicate Contig::General module is missed 
Then you could install this module by cpan syntax like:
       sudo cpan install Contig::General 





夏雨（XIA Yu）
助理教授 (Assistant Professor)
南方科技大学/工学院/环境科学与工程学院
广东省深圳市南山区学苑大道1088号

School of Environmental Science and Engineering, 
College of Engineering, Southern University of Science and
Technology (SUSTech), Shenzhen 518055, China


 
From: abigailvolk
Date: 2023-03-14 00:18
To: sustc-xylab/ARGpore2
CC: Subscribed
Subject: [sustc-xylab/ARGpore2] Error at Metaphlan2 Markergene database step (Issue #1)
Hi All,
I am attempting to download and use your tool. I installed the necessary dependencies in a Conda environment, cloned this repo, and used your directions to begin the database install. However, I'm getting an error at the Metaphlan2 Markergene database step:
`Downloading Metaphlan2 markergene database from git lfs
Updated Git hooks.
Git LFS initialized.
markers.fasta
Building lastdb for Metaphlan2 markergene database
Can't locate Bio/SeqIO.pm in @inc ***@***.*** contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /fs/ess/PAS1806/Abby/TOOLS/ARGpore2/bin/fastaNameLengh.pl line 23.
BEGIN failed--compilation aborted at /fs/ess/PAS1806/Abby/TOOLS/ARGpore2/bin/fastaNameLengh.pl line 23.`
Any ideas? Based on the error it seems that I do not have the Bio::SeqIO module. I have tried installing it into my Conda env conda install -c bioconda perl-bioperl but am still getting the error.

**Comment by wangyujie000** [comment]
Have you solved this problem yet? I alsoo have the same problem

**Comment by huall** [comment]
![image](https://github.com/sustc-xylab/ARGpore2/assets/12758463/a6203117-9003-4e59-bf49-dbed0fcc0c99)
你好 请问我这边为啥会报这个错误？

**Comment by sustc-xylab** [comment]
Seems your installation missed the database file.  or perhaps you didn't run  setup.sh before running argpore.sh. Please read the README carefully before running the tool.

cheers :)




夏雨（XIA Yu）
助理教授 (Assistant Professor)
南方科技大学/工学院/环境科学与工程学院
广东省深圳市南山区学苑大道1088号

School of Environmental Science and Engineering, 
College of Engineering, Southern University of Science and
Technology (SUSTech), Shenzhen 518055, China


 
From: huall
Date: 2023-10-18 17:18
To: sustc-xylab/ARGpore2
CC: shuixia100; Comment
Subject: Re: [sustc-xylab/ARGpore2] Error at Metaphlan2 Markergene database step (Issue #1)

你好 请问我这边为啥会报这个错误？

**Comment by huall** [comment]
![image](https://github.com/sustc-xylab/ARGpore2/assets/12758463/d75a73c5-ede6-4a1c-a7fc-8220e36b8a0c)
大佬，装到这里 会自动退出安装 ？
